name: go_flow
description: A simple implementation of go-lang's deffer statement, bringing it into dart-lang
version: 1.0.0
repository: https://github.com/fmotalleb/go_flow

environment:
  sdk: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
