name: go_flow
description: A simple implementation of go-lang's deffer statement, bringing it into dart-lang
version: 1.0.2
repository: https://github.com/fmotalleb/go_flow

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  moti_lints: ^1.0.0
  test: ^1.21.0
